
package ru.siblion.service.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LogSearchWSService", targetNamespace = "http://controller.siblion.ru/", wsdlLocation = "http://192.168.0.173:7001/LogSearchWS/LogSearchWSService?WSDL")
public class LogSearchWSService
    extends Service
{

    private final static URL LOGSEARCHWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGSEARCHWSSERVICE_EXCEPTION;
    private final static QName LOGSEARCHWSSERVICE_QNAME = new QName("http://controller.siblion.ru/", "LogSearchWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.173:7001/LogSearchWS/LogSearchWSService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGSEARCHWSSERVICE_WSDL_LOCATION = url;
        LOGSEARCHWSSERVICE_EXCEPTION = e;
    }

    public LogSearchWSService() {
        super(__getWsdlLocation(), LOGSEARCHWSSERVICE_QNAME);
    }

    public LogSearchWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGSEARCHWSSERVICE_QNAME, features);
    }

    public LogSearchWSService(URL wsdlLocation) {
        super(wsdlLocation, LOGSEARCHWSSERVICE_QNAME);
    }

    public LogSearchWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGSEARCHWSSERVICE_QNAME, features);
    }

    public LogSearchWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogSearchWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LogSearchWS
     */
    @WebEndpoint(name = "LogSearchWSPort")
    public LogSearchWS getLogSearchWSPort() {
        return super.getPort(new QName("http://controller.siblion.ru/", "LogSearchWSPort"), LogSearchWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogSearchWS
     */
    @WebEndpoint(name = "LogSearchWSPort")
    public LogSearchWS getLogSearchWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.siblion.ru/", "LogSearchWSPort"), LogSearchWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGSEARCHWSSERVICE_EXCEPTION!= null) {
            throw LOGSEARCHWSSERVICE_EXCEPTION;
        }
        return LOGSEARCHWSSERVICE_WSDL_LOCATION;
    }

}
