
package ru.siblion.client.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ConfigurationException", targetNamespace = "http://controller.service.siblion.ru/")
public class ConfigurationException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ConfigurationException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ConfigurationException_Exception(String message, ConfigurationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ConfigurationException_Exception(String message, ConfigurationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.siblion.client.soap.ConfigurationException
     */
    public ConfigurationException getFaultInfo() {
        return faultInfo;
    }

}
