
package ru.siblion.client.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LogSearchWS", targetNamespace = "http://controller.service.siblion.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LogSearchWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns ru.siblion.client.soap.SearchInfoResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logSearchSync", targetNamespace = "http://controller.service.siblion.ru/", className = "ru.siblion.client.soap.LogSearchSync")
    @ResponseWrapper(localName = "logSearchSyncResponse", targetNamespace = "http://controller.service.siblion.ru/", className = "ru.siblion.client.soap.LogSearchSyncResponse")
    @Action(input = "http://controller.service.siblion.ru/LogSearchWS/logSearchSyncRequest", output = "http://controller.service.siblion.ru/LogSearchWS/logSearchSyncResponse", fault = {
    })
    public SearchInfoResult logSearchSync(
        @WebParam(name = "arg0", targetNamespace = "")
        SearchInfo arg0)
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.siblion.client.soap.LogSearchResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logSearchAsync", targetNamespace = "http://controller.service.siblion.ru/", className = "ru.siblion.client.soap.LogSearchAsync")
    @ResponseWrapper(localName = "logSearchAsyncResponse", targetNamespace = "http://controller.service.siblion.ru/", className = "ru.siblion.client.soap.LogSearchAsyncResponse")
    @Action(input = "http://controller.service.siblion.ru/LogSearchWS/logSearchAsyncRequest", output = "http://controller.service.siblion.ru/LogSearchWS/logSearchAsyncResponse", fault = {
    })
    public LogSearchResult logSearchAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        SearchInfo arg0)
    ;

}
