
package ru.siblion.client.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SAXException", targetNamespace = "http://controller.service.siblion.ru/")
public class SAXException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SAXException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SAXException_Exception(String message, SAXException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SAXException_Exception(String message, SAXException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.siblion.client.soap.SAXException
     */
    public SAXException getFaultInfo() {
        return faultInfo;
    }

}
